export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILS = "PRODUCT_LIST_FAILs";

export const PRODUCT_SEARCH_LIST_REQUEST = "PRODUCT_SEARCH_LIST_REQUEST";
export const PRODUCT_SEARCH_LIST_SUCCESS = "PRODUCT_SEARCH_LIST_SUCCESS";
export const PRODUCT_SEARCH_LIST_FAILS = "PRODUCT_SEARCH_LIST_FAILs";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILS = "PRODUCT_DETAILS_FAILs";

export const PRODUCT_UPLOAD_REQUEST = "PRODUCT_UPLOAD_REQUEST";
export const PRODUCT_UPLOAD_SUCCESS = "PRODUCT_UPLOAD_SUCCESS";
export const PRODUCT_UPLOAD_FAILS = "PRODUCT_UPLOAD_FAILs";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAILS = "PRODUCT_UPDATE_FAILs";

export const PRODUCT_UPDATE_MANY_REQUEST = "PRODUCT_UPDATE_MANY_REQUEST";
export const PRODUCT_UPDATE_MANY_SUCCESS = "PRODUCT_UPDATE_MANY_SUCCESS";
export const PRODUCT_UPDATE_MANY_FAILS = "PRODUCT_UPDATE_MANY_FAILs";

export const PRODUCT_DELETE_MANY_REQUEST = "PRODUCT_DELETE_MANY_REQUEST";
export const PRODUCT_DELETE_MANY_SUCCESS = "PRODUCT_DELETE_MANY_SUCCESS";
export const PRODUCT_DELETE_MANY_FAILS = "PRODUCT_DELETE_MANY_FAILs";
