export const SELLER_ORDER_DETAILS_REQUEST = "SELLER_ORDER_DETAILS_REQUEST";
export const SELLER_ORDER_DETAILS_SUCCESS = "SELLER_ORDER_DETAILS_SUCCESS";
export const SELLER_ORDER_DETAILS_FAIL = "SELLER_ORDER_DETAILS_FAIL";
export const SELLER_ORDER_DETAILS_RESET = "SELLER_ORDER_DETAILS_RESET";


export const SHIPPED_ORDERS_REQUEST = "SHIPPED_ORDERS_REQUEST";
export const SHIPPED_ORDERS_SUCCESS = "SHIPPED_ORDERS_SUCCESS";
export const SHIPPED_ORDERS_FAIL = "SHIPPED_ORDERS_FAIL";

export const PENDING_ORDERS_REQUEST = "PENDING_ORDERS_REQUEST";
export const PENDING_ORDERS_SUCCESS = "PENDING_ORDERS_SUCCESS";
export const PENDING_ORDERS_FAIL = "PENDING_ORDERS_FAIL";

export const SEARCH_ORDERS_REQUEST = "SEARCH_ORDERS_REQUEST";
export const SEARCH_ORDERS_SUCCESS = "SEARCH_ORDERS_SUCCESS";
export const SEARCH_ORDERS_FAIL = "SEARCH_ORDERS_FAIL";




export const SELLER_ORDER_DELIVERY_REQUEST = "SELLER_ORDER_DELIVERY_REQUEST";
export const SELLER_ORDER_DELIVERY_SUCCESS = "SELLER_ORDER_DELIVERY_SUCCESS";
export const SELLER_ORDER_DELIVERY_FAIL = "SELLER_ORDER_DELIVERY_FAIL";
