export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL";
export const SELLER_LOGOUT = "SELLER_LOGOUT";
