export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_REQUEST = "USER_REG_REQUEST";
export const USER_REG_FAIL = "USER_REG_FAIL";

export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";
export const USER_DETAIL_RESET = "USER_DETAIL_RESET";


export const USER_DETAIL_UPDATE_SUCCESS = "USER_DETAIL_UPDATE_SUCCESS";
export const USER_DETAIL_UPDATE_REQUEST = "USER_DETAIL_UPDATE_REQUEST";
export const USER_DETAIL_UPDATE_FAIL = "USER_DETAIL_UPDATE_FAIL";


export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL";

export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";